export const founders = [
  {
    id: 1,
    name: "Emma Chen",
    photo: "https://images.unsplash.com/photo-1769636929132-e4e7b50cfac0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    startup: "EcoBox",
    industry: "Sustainable Packaging",
    fundingStatus: "Seed Round",
    fundingColor: "blue",
    lastSession: "Feb 12, 2026",
    readinessScore: 85,
  },
  {
    id: 2,
    name: "Priya Sharma",
    photo: "https://images.unsplash.com/photo-1573165706511-3ffde6ef1fe3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    startup: "HealthSync",
    industry: "HealthTech",
    fundingStatus: "Pre-Seed",
    fundingColor: "purple",
    lastSession: "Feb 10, 2026",
    readinessScore: 72,
  },
  {
    id: 3,
    name: "Sofia Rodriguez",
    photo: "https://images.unsplash.com/photo-1758369636875-60b3dcb76366?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    startup: "TechBridge Academy",
    industry: "EdTech",
    fundingStatus: "Series A",
    fundingColor: "green",
    lastSession: "Feb 14, 2026",
    readinessScore: 90,
  },
  {
    id: 4,
    name: "Lisa Anderson",
    photo: "https://images.unsplash.com/photo-1754298949882-216a1c92dbb5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    startup: "FoodChain",
    industry: "AgriTech",
    fundingStatus: "Bootstrapped",
    fundingColor: "yellow",
    lastSession: "Feb 8, 2026",
    readinessScore: 68,
  },
  {
    id: 5,
    name: "Maya Johnson",
    photo: "https://images.unsplash.com/photo-1573165706511-3ffde6ef1fe3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    startup: "CleanEnergy Solutions",
    industry: "CleanTech",
    fundingStatus: "Seed Round",
    fundingColor: "blue",
    lastSession: "Feb 13, 2026",
    readinessScore: 78,
  },
  {
    id: 6,
    name: "Aisha Patel",
    photo: "https://images.unsplash.com/photo-1769636929132-e4e7b50cfac0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=400",
    startup: "FinanceFirst",
    industry: "FinTech",
    fundingStatus: "Pre-Seed",
    fundingColor: "purple",
    lastSession: "Feb 11, 2026",
    readinessScore: 75,
  },
];